### ISSUE TITLE
[Bug]: webpack_devserver doesn't seem to be including transitive deps of npm packages

### ISSUE THREAD

**Issue by gregjacobs** [aspect-build/rules_webpack#66]
### What happened?

This worked okay in `0.3.0`, but in `0.5.1`, `webpack_devserver` doesn't seem to be including transitive dependencies of plugins at runtime.

For instance, I'm using `html-webpack-plugin`, but it can't find the dependencies of `html-webpack-plugin` at runtime:

```
[webpack-cli] Error: Cannot find module 'lodash'
Require stack:
- /private/var/folders/80/qbf5kjns6dxb7ygw_5_fllmj02xdrp/T/js_run_devserver-fNG3En/uitoolkit/node_modules/html-webpack-plugin/index.js
- /private/var/folders/80/qbf5kjns6dxb7ygw_5_fllmj02xdrp/T/js_run_devserver-fNG3En/uitoolkit/build-tools/webpack.config.js
```

And if I add `//:node_modules/lodash` as a direct dependency, it complains about not finding the next dependency ('pretty-error' in this case)

### Version

Development (host) and target OS/architectures: MacOS Monterey

Output of `bazel --version`: 5.3.0

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file: rules_webpack 0.5.1, rules_js 1.6.7

Language(s) and/or frameworks involved:

### How to reproduce

```shell
webpack_devserver(
    name = "devserver",
    data = [
        "//:node_modules/html-webpack-plugin",
        "index.js"
    ],
    webpack_config = "webpack.config.js",
)
```

### Any other information?

It seems there's a test in `webpack/test/devserver` that looks like it demonstrates that this should work correctly, but maybe it isn't actually executed as a test on a CI runner?

### Fund our work

- [ ] Sponsor our open source work by donating a [bug bounty](https://opencollective.com/aspect-build/)

**Comment by gregmagolan** [comment]
The webpack_devserver was re-wired to use a more compatible js_run_devserver under the hood. This solves the watch mode problem in a general way. Tho it is quite possible that transitive deps were broken with the change. I'll put this on my list to look at next week.

**Comment by gregmagolan** [comment]
This should fix the underlying issue: https://github.com/aspect-build/rules_js/pull/596

**Comment by gregmagolan** [comment]
Related to Bazel Slack question https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1667857230697759

**Comment by gregmagolan** [comment]
Fix included in rules_webpack 0.5.2 release

**Comment by gregjacobs** [comment]
Awesome, thanks for looking into this!

**Comment by gregjacobs** [comment]
Oof, just tried with rules_webpack@0.5.2 and rules_js@1.6.8 and still having the same issue. Trying to use `html-webpack-plugin` results in the same `Error: Cannot find module 'lodash'` error

**Comment by alex-torok** [comment]
I hit the same issue and think the problem is related to the patched fs module enforcing the bazel sandbox. I don't have a reproduction available right now, but followed roughly this path:
